[2024-08-31T03:02:14.746+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T03:01:03.383411+00:00 [queued]>
[2024-08-31T03:02:14.808+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T03:01:03.383411+00:00 [queued]>
[2024-08-31T03:02:14.821+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T03:02:15.169+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 03:01:03.383411+00:00
[2024-08-31T03:02:15.230+0000] {standard_task_runner.py:60} INFO - Started process 1415 to run task
[2024-08-31T03:02:15.241+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T03:01:03.383411+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpkibrq2yn']
[2024-08-31T03:02:15.329+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask spark_retail_analysis_task
[2024-08-31T03:02:15.536+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T03:02:15.743+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T03:01:03.383411+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T03:02:16.656+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T03:01:03.383411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T03:01:03.383411+00:00'
[2024-08-31T03:02:16.730+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-31T03:02:16.753+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-31T03:03:37.092+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-31T03:03:37.104+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-31T03:03:37.112+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-31T03:03:37.122+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-31T03:03:37.130+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-31T03:03:37.132+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-31T03:03:37.135+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-31T03:03:37.137+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-31T03:03:37.139+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-31T03:03:37.140+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-31T03:03:37.142+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-31T03:03:37.914+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T03:03:38.016+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T030103, start_date=20240831T030214, end_date=20240831T030337
[2024-08-31T03:03:38.234+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 1415)
[2024-08-31T03:03:38.291+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T03:03:38.413+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
