[2024-08-30T15:34:55.161+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-30T15:34:50.927552+00:00 [queued]>
[2024-08-30T15:34:55.175+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-30T15:34:50.927552+00:00 [queued]>
[2024-08-30T15:34:55.177+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-08-30T15:34:55.211+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-30 15:34:50.927552+00:00
[2024-08-30T15:34:55.233+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-30T15:34:50.927552+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpbm84_yz6']
[2024-08-30T15:34:55.238+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask spark_retail_analysis_task
[2024-08-30T15:34:55.219+0000] {standard_task_runner.py:60} INFO - Started process 5705 to run task
[2024-08-30T15:34:55.298+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-30T15:34:55.397+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-30T15:34:50.927552+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-30T15:34:55.768+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T15:34:50.927552+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-30T15:34:50.927552+00:00'
[2024-08-30T15:34:55.799+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-30T15:34:55.802+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=/usr/bin/python3 --conf spark.yarn.appMasterEnv.SPARK_HOME=/path/to/spark --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-30T15:34:55.870+0000] {spark_submit.py:579} INFO - /home/airflow/.local/bin/spark-submit: line 27: /path/to/spark/bin/spark-class: No such file or directory
[2024-08-30T15:34:55.888+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=/usr/bin/python3 --conf spark.yarn.appMasterEnv.SPARK_HOME=/path/to/spark --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 127.
[2024-08-30T15:34:55.900+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240830T153450, start_date=20240830T153455, end_date=20240830T153455
[2024-08-30T15:34:55.938+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=/usr/bin/python3 --conf spark.yarn.appMasterEnv.SPARK_HOME=/path/to/spark --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 127.; 5705)
[2024-08-30T15:34:55.971+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T15:34:56.010+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
