[2024-08-31T03:20:01.018+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T03:19:50.254818+00:00 [queued]>
[2024-08-31T03:20:01.047+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T03:19:50.254818+00:00 [queued]>
[2024-08-31T03:20:01.051+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T03:20:01.107+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 03:19:50.254818+00:00
[2024-08-31T03:20:01.127+0000] {standard_task_runner.py:60} INFO - Started process 2024 to run task
[2024-08-31T03:20:01.140+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T03:19:50.254818+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmp88n8nhfm']
[2024-08-31T03:20:01.147+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask spark_retail_analysis_task
[2024-08-31T03:20:01.220+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T03:20:01.438+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T03:19:50.254818+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T03:20:01.831+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T03:19:50.254818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T03:19:50.254818+00:00'
[2024-08-31T03:20:01.881+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-31T03:20:01.894+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-31T03:20:18.133+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-31T03:20:18.154+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-31T03:20:18.156+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-31T03:20:18.164+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-31T03:20:18.171+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-31T03:20:18.184+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-31T03:20:18.204+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-31T03:20:18.206+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-31T03:20:18.220+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-31T03:20:18.224+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-31T03:20:18.246+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-31T03:20:18.318+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T03:20:18.349+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T031950, start_date=20240831T032001, end_date=20240831T032018
[2024-08-31T03:20:18.521+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 42 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 2024)
[2024-08-31T03:20:18.665+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T03:20:18.722+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
