[2024-08-30T15:16:05.993+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-30T15:16:00.908024+00:00 [queued]>
[2024-08-30T15:16:06.015+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-30T15:16:00.908024+00:00 [queued]>
[2024-08-30T15:16:06.021+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-08-30T15:16:06.059+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-30 15:16:00.908024+00:00
[2024-08-30T15:16:06.077+0000] {standard_task_runner.py:60} INFO - Started process 4864 to run task
[2024-08-30T15:16:06.108+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-30T15:16:00.908024+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpu5dx4pib']
[2024-08-30T15:16:06.113+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask spark_retail_analysis_task
[2024-08-30T15:16:06.706+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-30T15:16:07.032+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-30T15:16:00.908024+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-30T15:16:08.247+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T15:16:00.908024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-30T15:16:00.908024+00:00'
[2024-08-30T15:16:08.393+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-30T15:16:08.396+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-30T15:16:27.058+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-30T15:16:27.060+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-30T15:16:27.066+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-30T15:16:27.067+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-30T15:16:27.067+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-30T15:16:27.068+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-30T15:16:27.070+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-30T15:16:27.070+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-30T15:16:27.071+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-30T15:16:27.072+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-30T15:16:27.074+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-30T15:16:27.125+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-30T15:16:27.138+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240830T151600, start_date=20240830T151605, end_date=20240830T151627
[2024-08-30T15:16:27.178+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 4864)
[2024-08-30T15:16:27.257+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T15:16:27.325+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
