[2024-08-31T19:35:08.964+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:35:02.743697+00:00 [queued]>
[2024-08-31T19:35:09.011+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:35:02.743697+00:00 [queued]>
[2024-08-31T19:35:09.013+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T19:35:09.105+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 19:35:02.743697+00:00
[2024-08-31T19:35:09.131+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T19:35:02.743697+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmp70_p4wjf']
[2024-08-31T19:35:09.132+0000] {standard_task_runner.py:60} INFO - Started process 17629 to run task
[2024-08-31T19:35:09.138+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask spark_retail_analysis_task
[2024-08-31T19:35:09.239+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T19:35:09.604+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:35:02.743697+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T19:35:10.336+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T19:35:02.743697+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T19:35:02.743697+00:00'
[2024-08-31T19:35:10.377+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-08-31T19:35:10.385+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-08-31T19:35:17.045+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-31T19:35:17.484+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-08-31T19:35:17.485+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-08-31T19:35:17.520+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-08-31T19:35:17.526+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-dbe7ccbb-d583-4d43-9ecf-09caf77dbd40;1.0
[2024-08-31T19:35:17.526+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:35:18.135+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-08-31T19:35:18.797+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-31T19:35:18.919+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 1374ms :: artifacts dl 19ms
[2024-08-31T19:35:18.921+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-08-31T19:35:18.926+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-31T19:35:18.929+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-08-31T19:35:18.947+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:35:18.949+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-08-31T19:35:18.949+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-31T19:35:18.950+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:35:18.951+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-08-31T19:35:18.951+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:35:18.952+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-dbe7ccbb-d583-4d43-9ecf-09caf77dbd40
[2024-08-31T19:35:18.952+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:35:18.975+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/39ms)
[2024-08-31T19:35:20.681+0000] {spark_submit.py:579} INFO - 24/08/31 19:35:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-31T19:35:25.883+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-08-31T19:35:25.884+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 20, in <module>
[2024-08-31T19:35:25.893+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-08-31T19:35:25.896+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-08-31T19:35:26.045+0000] {spark_submit.py:579} INFO - 24/08/31 19:35:26 INFO ShutdownHookManager: Shutdown hook called
[2024-08-31T19:35:26.047+0000] {spark_submit.py:579} INFO - 24/08/31 19:35:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-13e93e15-ea5d-42a0-818f-a177e5330cbe
[2024-08-31T19:35:26.302+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T19:35:26.318+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T193502, start_date=20240831T193508, end_date=20240831T193526
[2024-08-31T19:35:26.362+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 63 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 17629)
[2024-08-31T19:35:26.435+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T19:35:26.468+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
